name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
    DOCKER_USER: thijswithaar
    DBUILDOPTS: "" #--squash"

jobs:
  windows_msys:
    if: ${{ false }} # This hangs on pacman installation
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build ${{ env.DBUILDOPTS }} -f Dockerfile.windows_msys -t ${{ env.DOCKER_USER }}/windows:msys .

  windows_2019:
    if: ${{ false }}
    # Qt takes ~2 hours to build
    timeout-minutes: 360
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build ${DBUILDOPTS} -f Dockerfile.windows_2019 -t ${{ env.DOCKER_USER }}/windows:2019 .
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker image push thijswithaar/windows:2019

  windows_2022:
    # Qt takes ~2 hours to build
    timeout-minutes: 360
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build ${DBUILDOPTS} -f Dockerfile.windows_2022 -t ${{ env.DOCKER_USER }}/windows:2022 .
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker image push thijswithaar/windows:2022

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          ./build.sh
