name: Build Docker Images

on: [push]

env:
    DOCKER_USER: thijswithaar
    DBUILDOPTS: "--pull --no-cache --squash"

jobs:
  docker_windows:
    # Qt takes ~2 hours to build
    timeout-minutes: 360
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build ${DBUILDOPTS} -f Dockerfile.windows -t ${{ env.DOCKER_USER }}/windows:2019 .
          docker image push thijswithaar/windows:2019
